// Currency data for Currency Converter
const CURRENCIES = {
  USD: { name: 'US Dollar', symbol: '$' },
  EUR: { name: 'Euro', symbol: '€' },
  GBP: { name: 'British Pound', symbol: '£' },
  JPY: { name: 'Japanese Yen', symbol: '¥' },
  AUD: { name: 'Australian Dollar', symbol: 'A$' },
  CAD: { name: 'Canadian Dollar', symbol: 'C$' },
  CHF: { name: 'Swiss Franc', symbol: 'CHF' },
  CNY: { name: 'Chinese Yuan', symbol: '¥' },
  SEK: { name: 'Swedish Krona', symbol: 'kr' },
  NZD: { name: 'New Zealand Dollar', symbol: 'NZ$' },
  MXN: { name: 'Mexican Peso', symbol: '$' },
  SGD: { name: 'Singapore Dollar', symbol: 'S$' },
  HKD: { name: 'Hong Kong Dollar', symbol: 'HK$' },
  NOK: { name: 'Norwegian Krone', symbol: 'kr' },
  TRY: { name: 'Turkish Lira', symbol: '₺' },
  RUB: { name: 'Russian Ruble', symbol: '₽' },
  INR: { name: 'Indian Rupee', symbol: '₹' },
  BRL: { name: 'Brazilian Real', symbol: 'R$' },
  ZAR: { name: 'South African Rand', symbol: 'R' },
  DKK: { name: 'Danish Krone', symbol: 'kr' },
  PLN: { name: 'Polish Zloty', symbol: 'zł' },
  TWD: { name: 'Taiwan Dollar', symbol: 'NT$' },
  THB: { name: 'Thai Baht', symbol: '฿' },
  MYR: { name: 'Malaysian Ringgit', symbol: 'RM' },
  IDR: { name: 'Indonesian Rupiah', symbol: 'Rp' },
  PHP: { name: 'Philippine Peso', symbol: '₱' },
  CZK: { name: 'Czech Koruna', symbol: 'Kč' },
  HUF: { name: 'Hungarian Forint', symbol: 'Ft' },
  ILS: { name: 'Israeli Shekel', symbol: '₪' },
  CLP: { name: 'Chilean Peso', symbol: '$' },
  PKR: { name: 'Pakistani Rupee', symbol: '₨' },
  AED: { name: 'UAE Dirham', symbol: 'د.إ' },
  SAR: { name: 'Saudi Riyal', symbol: '﷼' },
  KRW: { name: 'South Korean Won', symbol: '₩' },
  BDT: { name: 'Bangladeshi Taka', symbol: '৳' },
  VND: { name: 'Vietnamese Dong', symbol: '₫' },
  ARS: { name: 'Argentine Peso', symbol: '$' },
  COP: { name: 'Colombian Peso', symbol: '$' },
  EGP: { name: 'Egyptian Pound', symbol: '£' },
  NGN: { name: 'Nigerian Naira', symbol: '₦' },
  RON: { name: 'Romanian Leu', symbol: 'lei' },
  UAH: { name: 'Ukrainian Hryvnia', symbol: '₴' },
  KZT: { name: 'Kazakhstani Tenge', symbol: '₸' },
  QAR: { name: 'Qatari Riyal', symbol: '﷼' },
  KWD: { name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  BHD: { name: 'Bahraini Dinar', symbol: '.د.ب' },
  OMR: { name: 'Omani Rial', symbol: '﷼' },
  JOD: { name: 'Jordanian Dinar', symbol: 'د.ا' },
  LKR: { name: 'Sri Lankan Rupee', symbol: '₨' },
  BGN: { name: 'Bulgarian Lev', symbol: 'лв' },
  HRK: { name: 'Croatian Kuna', symbol: 'kn' },
  ISK: { name: 'Icelandic Krona', symbol: 'kr' },
  RSD: { name: 'Serbian Dinar', symbol: 'дин' },
  LBP: { name: 'Lebanese Pound', symbol: '£' },
  JMD: { name: 'Jamaican Dollar', symbol: 'J$' },
  BOB: { name: 'Bolivian Boliviano', symbol: 'Bs.' },
  PYG: { name: 'Paraguayan Guaraní', symbol: '₲' },
  UYU: { name: 'Uruguayan Peso', symbol: '$U' },
  PEN: { name: 'Peruvian Sol', symbol: 'S/.' },
  DOP: { name: 'Dominican Peso', symbol: 'RD$' },
  GTQ: { name: 'Guatemalan Quetzal', symbol: 'Q' },
  CRC: { name: 'Costa Rican Colón', symbol: '₡' },
  PAB: { name: 'Panamanian Balboa', symbol: 'B/.' },
  HNL: { name: 'Honduran Lempira', symbol: 'L' },
  NIO: { name: 'Nicaraguan Córdoba', symbol: 'C$' },
  BZD: { name: 'Belize Dollar', symbol: 'BZ$' },
  TTD: { name: 'Trinidad and Tobago Dollar', symbol: 'TT$' },
  BBD: { name: 'Barbadian Dollar', symbol: 'Bds$' },
  BSD: { name: 'Bahamian Dollar', symbol: 'B$' },
  XCD: { name: 'East Caribbean Dollar', symbol: '$' },
  AWG: { name: 'Aruban Florin', symbol: 'ƒ' },
  ANG: { name: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
  FJD: { name: 'Fijian Dollar', symbol: 'FJ$' },
  PGK: { name: 'Papua New Guinean Kina', symbol: 'K' },
  SBD: { name: 'Solomon Islands Dollar', symbol: 'SI$' },
  VUV: { name: 'Vanuatu Vatu', symbol: 'Vt' },
  WST: { name: 'Samoan Tala', symbol: 'T' },
  TOP: { name: 'Tongan Paʻanga', symbol: 'T$' },
  XPF: { name: 'CFP Franc', symbol: '₣' },
  MOP: { name: 'Macanese Pataca', symbol: 'MOP$' },
  KHR: { name: 'Cambodian Riel', symbol: '៛' },
  LAK: { name: 'Lao Kip', symbol: '₭' },
  MMK: { name: 'Myanmar Kyat', symbol: 'K' },
  BND: { name: 'Brunei Dollar', symbol: 'B$' },
  LSL: { name: 'Lesotho Loti', symbol: 'L' },
  SZL: { name: 'Swazi Lilangeni', symbol: 'E' },
  BWP: { name: 'Botswana Pula', symbol: 'P' },
  MZN: { name: 'Mozambican Metical', symbol: 'MT' },
  MGA: { name: 'Malagasy Ariary', symbol: 'Ar' },
  MUR: { name: 'Mauritian Rupee', symbol: '₨' },
  SCR: { name: 'Seychellois Rupee', symbol: '₨' },
  KES: { name: 'Kenyan Shilling', symbol: 'KSh' },
  TZS: { name: 'Tanzanian Shilling', symbol: 'TSh' },
  UGX: { name: 'Ugandan Shilling', symbol: 'USh' },
  RWF: { name: 'Rwandan Franc', symbol: 'RF' },
  ETB: { name: 'Ethiopian Birr', symbol: 'Br' },
  SOS: { name: 'Somali Shilling', symbol: 'S' },
  DJF: { name: 'Djiboutian Franc', symbol: 'Fdj' },
  ERN: { name: 'Eritrean Nakfa', symbol: 'Nfk' },
  SDG: { name: 'Sudanese Pound', symbol: 'ج.س.' },
  SSP: { name: 'South Sudanese Pound', symbol: '£' },
  AOA: { name: 'Angolan Kwanza', symbol: 'Kz' },
  ZMW: { name: 'Zambian Kwacha', symbol: 'ZK' },
  MWK: { name: 'Malawian Kwacha', symbol: 'MK' },
  MNT: { name: 'Mongolian Tugrik', symbol: '₮' },
  NPR: { name: 'Nepalese Rupee', symbol: '₨' },
  BTN: { name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  AFN: { name: 'Afghan Afghani', symbol: '؋' },
  IRR: { name: 'Iranian Rial', symbol: '﷼' },
  IQD: { name: 'Iraqi Dinar', symbol: 'ع.د' },
  SYP: { name: 'Syrian Pound', symbol: '£' },
  YER: { name: 'Yemeni Rial', symbol: '﷼' },
  AMD: { name: 'Armenian Dram', symbol: '֏' },
  AZN: { name: 'Azerbaijani Manat', symbol: '₼' },
  GEL: { name: 'Georgian Lari', symbol: '₾' },
  MDL: { name: 'Moldovan Leu', symbol: 'lei' },
  BYN: { name: 'Belarusian Ruble', symbol: 'Br' },
  ALL: { name: 'Albanian Lek', symbol: 'L' },
  MKD: { name: 'Macedonian Denar', symbol: 'ден' },
  BAM: { name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
  XDR: { name: 'Special Drawing Rights', symbol: 'SDR' },
};

// Make CURRENCIES available globally
if (typeof window !== 'undefined') {
  window.CURRENCIES = CURRENCIES;
}
